# Ray Casting
asset:
  path: assets/objaverse/minivan/model.glb

camera:
  angle_x: 0.9 # Field of view in radians (e.g., 0.9 radians ≈ 51.6 degrees)

rendering:
  views:
    # Top-down view (camera above looking down)
    - azimuth: 0
      elevation: 90
      radius: 3

    # Slightly elevated views with different azimuths
    - azimuth: 45
      elevation: 30
      radius: 3
    - azimuth: 135
      elevation: 30
      radius: 3
    - azimuth: 225
      elevation: 30
      radius: 3
    - azimuth: 315
      elevation: 30
      radius: 3
  max_hits: 4
  height: 512
  width: 512

output:
  rc: output/ray_casting
  texture: output/texture

# Depth to Image Generation
controlnet:
  depth_model: lllyasviel/sd-controlnet-depth
  canny_model: lllyasviel/sd-controlnet-canny
stable_diffusion:
  model: runwayml/stable-diffusion-v1-5
  num_steps: 20
stylization:
  image_path: output/ray_casting/model/0_0_90_3/hit_0.png
  text_condition: Top View of Red Minivan
  type: canny # Choose from: [depth, canny]

# Instant Style