# Ray Casting
asset:
  path: assets/rabbit.glb

camera:
  angle_x: 0.9 # Field of view in radians (e.g., 0.9 radians ≈ 51.6 degrees)

rendering:
  views:
    # Top-down view (camera above looking down)
    - azimuth: 0
      elevation: 90
      radius: 1.5

    # Slightly elevated views with different azimuths
    - azimuth: 45
      elevation: 30
      radius: 1
    - azimuth: 135
      elevation: 30
      radius: 1
    - azimuth: 225
      elevation: 30
      radius: 1
    - azimuth: 315
      elevation: 30
      radius: 1
  max_hits: 4
  height: 512
  width: 512

  output:
    rc: output/ray_casting
    texture: output/texture

  # Depth to Image Generation
  depth_model: lllyasviel/sd-controlnet-depth
  stable_diffusion:
    model: runwayml/stable-diffusion-v1-5
    num_steps: 20
  text_condition: Red Rabbit

  # Controlnet